#!/usr/bin/env python

###############################################################################
#   Copyright 2010 The University of Texas at Austin                          #
#                                                                             #
#   Licensed under the Apache License, Version 2.0 (the "License");           #
#   you may not use this file except in compliance with the License.          #
#   You may obtain a copy of the License at                                   #
#                                                                             #
#       http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                             #
#   Unless required by applicable law or agreed to in writing, software       #
#   distributed under the License is distributed on an "AS IS" BASIS,         #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
#   See the License for the specific language governing permissions and       #
#   limitations under the License.                                            #
###############################################################################

import getopt
import httplib
import os
import sys

if "KARNAK_HOST" in os.environ:
    host = os.environ["KARNAK_HOST"]
else:
    host = "karnak.teragrid.org"

if "KARNAK_PORT" in os.environ:
    port = int(os.environ["KARNAK_PORT"])
else:
    port = 80


def usage():
    print("usage: kstart [--help | [--text | --xml | --html]] <system name> <job identifier>")
    print("  --help          prints this help message")
    print("  -t or --text    requests output formated as plain text (default")
    print("  -x or --xml     requests output formated as XML")
    print("  -h or --html    requests output formated as HTML")
    print("  system name     the name of the batch scheduled system (required)")
    print("  job identifier  the job identifier assigned to the job by the batch scheduler (required)")


if __name__ == "__main__":
    try:
        opts, args = getopt.gnu_getopt(sys.argv[1:], "txh", ["text", "xml", "html","help"])
    except getopt.GetoptError, err:
        print str(err)
        usage()
        sys.exit(2)

    format = "txt"
    headers = {"Content-type": "text/plain",
               "Accept": "text/plain"}
    for opt, arg in opts:
        if opt == "--help":
            usage()
            sys.exit(0)
        elif opt in ("-t", "--text"):
            # defaults
            pass
        elif opt in ("-x", "--xml"):
            format = "xml"
            headers = {"Content-type": "text/xml",
                       "Accept": "text/xml"}
        elif opt in ("-h", "--html"):
            format = "html"
            headers = {"Content-type": "text/html",
                       "Accept": "text/html"}
        else:
            assert False, "unhandled option"

    if len(args) < 1 or len(args) > 2:
        usage()
        sys.exit(1)

    conn = httplib.HTTPConnection(host,port)
    conn.request("GET","/karnak/system/"+args[0]+"/job/"+args[1]+"/prediction/starttime."+format,"",headers)
    r = conn.getresponse()
    data = r.read()
    conn.close()
    if r.status != httplib.OK:
        print ("request failed: "+r.reason+" ("+str(r.status)+")")
        sys.exit(1)
    print(data)
