#!/usr/bin/env python

###############################################################################
#   Copyright 2010 The University of Texas at Austin                          #
#                                                                             #
#   Licensed under the Apache License, Version 2.0 (the "License");           #
#   you may not use this file except in compliance with the License.          #
#   You may obtain a copy of the License at                                   #
#                                                                             #
#       http://www.apache.org/licenses/LICENSE-2.0                            #
#                                                                             #
#   Unless required by applicable law or agreed to in writing, software       #
#   distributed under the License is distributed on an "AS IS" BASIS,         #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #
#   See the License for the specific language governing permissions and       #
#   limitations under the License.                                            #
###############################################################################

import getopt
import httplib
import os
import sys

if "KARNAK_HOST" in os.environ:
    host = os.environ["KARNAK_HOST"]
else:
    host = "karnak.teragrid.org"

if "KARNAK_PORT" in os.environ:
    port = int(os.environ["KARNAK_PORT"])
else:
    port = 80


def usage():
    print("usage: ksystems [--help | [--text | --xml | --html]]")
    print("  --help          prints this help message")
    print("  -t or --text    requests output formatted as plain text (default")
    print("  -x or --xml     requests output formatted as XML")
    print("  -j or --json    requests output formatted as JSON")
    print("  -h or --html    requests output formatted as HTML")


if __name__ == "__main__":
    try:
        opts, args = getopt.gnu_getopt(sys.argv[1:], "txhj", ["text","xml","json","html","help"])
    except getopt.GetoptError, err:
        print str(err)
        usage()
        sys.exit(2)

    format = "txt"
    for opt, arg in opts:
        if opt == "--help":
            usage()
            sys.exit(0)
        elif opt in ("-t", "--text"):
            format = "txt"
        elif opt in ("-x", "--xml"):
            format = "xml"
        elif opt in ("-j", "--json"):
            format = "json"
        elif opt in ("-h", "--html"):
            format = "html"
        else:
            assert False, "unhandled option"

    conn = httplib.HTTPConnection(host,port)
    conn.request("GET","/karnak/system/status."+format)
    r = conn.getresponse()
    data = r.read()
    conn.close()
    if r.status != httplib.OK:
        print("request failed: "+r.reason+" ("+str(r.status)+")")
        sys.exit(1)
    print(data)
